image: node:10
build:
  artifacts:
    paths:
      - public
  stage: build
  script:
    - npm i
    - npm run build
pages:
  artifacts:
    paths:
      - public
  script:
    - echo "Hello" 
     only:
    - develop